server:
  port: 8080 # 服务端口：Auth Server 运行在 8080#
  #建议同时开启这个，让 Spring 能够识别代理传来的 Header
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: AUTH_SESSIONID # 【关键】自定义 Cookie 名称，隔离会话
        domain: civer.cn # 注意前面的点，允许所有子域名共享

spring:
  config:
    import: optional:file:./application-secret.yml
#spring:
#  config:
#    import:
#      - "optional:file:application-secret.yml"
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb # 数据库连接地址
    username: username # 数据库用户名
    password: password # 数据库密码
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always # always: 每次启动尝试运行 schema.sql (如果存在)
  jpa:
    hibernate:
      ddl-auto: update # update: 自动根据 Entity 更新表结构，不会删除数据
    show-sql: true # 控制台打印 SQL，方便调试
    open-in-view: false # 显式关闭 Open Session in View，避免视图层访问数据库
  security:
    oauth2:
      authorizationserver:
        issuer: ${app.base-url}



app:
  # 认证中心对外 issuer（tidp 部署时须为 https://tidp.civer.cn），与各客户端 issuer-uri 一致，否则 backchannel logout 验签失败
  base-url: ${APP_BASE_URL:http://127.0.0.1:8080}
  # 底部备案信息（留空则不显示）
  footer:
    icp: "蜀ICP备2025159968号-1" # 例如：京ICP备xxxxxxxx号
    icp-url: "https://beian.miit.gov.cn/"
    icp-icon: "/images/icp.png" # ICP 备案图标。静态文件放 static 目录下，URL 用 /images/xxx.png（不要写 /static）
    police: "川公网安备51012402001520号" # 例如：京公网安备xxxxxxxxxxxx号
    police-url: "https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=51012402001520" # 公安备案查询链接，如各省公安厅备案查询页
    police-icon: "/images/beian.png" # 公安备案图标，同上，路径为 /images/xxx.png

  auth:
    # Initial Client Data (Auto-registered on startup if missing)
    initial-client:
      client-id: client-usermanage
      client-secret: secret
      # 支持多个 URI，用逗号分隔
      redirect-uris: http://127.0.0.1:8081/login/oauth2/code/oidc-client
      post-logout-redirect-uri: http://127.0.0.1:8080/login

# TODO： Spring Security 自带保存上次请求路径，需要修改默认的登录成功处理器，将请求路径保存到 session 中
# 登录成功后，若保存的请求是 /error（或 /error?*），则改为重定向到 /，避免出现“登录成功却跳到错误页”的现象。